<?php

namespace AppBundle\Repository\User;

/**
 * SuperAdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperAdminUserRepository extends \Doctrine\ORM\EntityRepository
{
}
